name: CI/CD Pipeline

on:
  push:
    branches:
      - main
env:
  IMAGE_URL: ccr.ccs.tencentyun.com/peil/fanatest

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run pytest
      run: pytest

    - name: Build Docker image
      run: docker build -t ${IMAGE_URL}:${GITHUB_SHA} .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.CLOUD_ACCOUNT_ID }} -p '${{ secrets.REGISTRY_PASSWORD }}' ${IMAGE_URL}

    - name: Push Docker image
      run: docker push ${IMAGE_URL}:${GITHUB_SHA}

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 43.143.97.40
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Your deployment script here, e.g., pull and run the Docker image
          docker pull ${IMAGE_URL}:${GITHUB_SHA}
          docker run -d --name pytest -p 80:80 ${IMAGE_URL}:${GITHUB_SHA}
